# Generated by Django 6.0.3 on 2026-04-01 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_task_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='completed',
            new_name='is_completed',
        ),
    ]
